/** Catálogo estático de países (nombres en español + código telefónico), sin API externa. */
export interface Country {
  name: string;
  dial: string;
}

export const COUNTRIES: Country[] = [
  { name: "Afganistán", dial: "+93" },
  { name: "Albania", dial: "+355" },
  { name: "Alemania", dial: "+49" },
  { name: "Andorra", dial: "+376" },
  { name: "Angola", dial: "+244" },
  { name: "Antigua y Barbuda", dial: "+1268" },
  { name: "Arabia Saudita", dial: "+966" },
  { name: "Argelia", dial: "+213" },
  { name: "Argentina", dial: "+54" },
  { name: "Armenia", dial: "+374" },
  { name: "Australia", dial: "+61" },
  { name: "Austria", dial: "+43" },
  { name: "Azerbaiyán", dial: "+994" },
  { name: "Bahamas", dial: "+1242" },
  { name: "Bangladés", dial: "+880" },
  { name: "Barbados", dial: "+1246" },
  { name: "Baréin", dial: "+973" },
  { name: "Bélgica", dial: "+32" },
  { name: "Belice", dial: "+501" },
  { name: "Benín", dial: "+229" },
  { name: "Bielorrusia", dial: "+375" },
  { name: "Bolivia", dial: "+591" },
  { name: "Bosnia y Herzegovina", dial: "+387" },
  { name: "Botsuana", dial: "+267" },
  { name: "Brasil", dial: "+55" },
  { name: "Brunéi", dial: "+673" },
  { name: "Bulgaria", dial: "+359" },
  { name: "Burkina Faso", dial: "+226" },
  { name: "Burundi", dial: "+257" },
  { name: "Bután", dial: "+975" },
  { name: "Cabo Verde", dial: "+238" },
  { name: "Camboya", dial: "+855" },
  { name: "Camerún", dial: "+237" },
  { name: "Canadá", dial: "+1" },
  { name: "Catar", dial: "+974" },
  { name: "Chad", dial: "+235" },
  { name: "Chile", dial: "+56" },
  { name: "China", dial: "+86" },
  { name: "Chipre", dial: "+357" },
  { name: "Colombia", dial: "+57" },
  { name: "Comoras", dial: "+269" },
  { name: "Corea del Norte", dial: "+850" },
  { name: "Corea del Sur", dial: "+82" },
  { name: "Costa de Marfil", dial: "+225" },
  { name: "Costa Rica", dial: "+506" },
  { name: "Croacia", dial: "+385" },
  { name: "Cuba", dial: "+53" },
  { name: "Dinamarca", dial: "+45" },
  { name: "Dominica", dial: "+1767" },
  { name: "Ecuador", dial: "+593" },
  { name: "Egipto", dial: "+20" },
  { name: "El Salvador", dial: "+503" },
  { name: "Emiratos Árabes Unidos", dial: "+971" },
  { name: "Eritrea", dial: "+291" },
  { name: "Eslovaquia", dial: "+421" },
  { name: "Eslovenia", dial: "+386" },
  { name: "España", dial: "+34" },
  { name: "Estados Unidos", dial: "+1" },
  { name: "Estonia", dial: "+372" },
  { name: "Esuatini", dial: "+268" },
  { name: "Etiopía", dial: "+251" },
  { name: "Filipinas", dial: "+63" },
  { name: "Finlandia", dial: "+358" },
  { name: "Fiyi", dial: "+679" },
  { name: "Francia", dial: "+33" },
  { name: "Gabón", dial: "+241" },
  { name: "Gambia", dial: "+220" },
  { name: "Georgia", dial: "+995" },
  { name: "Ghana", dial: "+233" },
  { name: "Granada", dial: "+1473" },
  { name: "Grecia", dial: "+30" },
  { name: "Guatemala", dial: "+502" },
  { name: "Guinea", dial: "+224" },
  { name: "Guinea-Bisáu", dial: "+245" },
  { name: "Guinea Ecuatorial", dial: "+240" },
  { name: "Guyana", dial: "+592" },
  { name: "Haití", dial: "+509" },
  { name: "Honduras", dial: "+504" },
  { name: "Hungría", dial: "+36" },
  { name: "India", dial: "+91" },
  { name: "Indonesia", dial: "+62" },
  { name: "Irak", dial: "+964" },
  { name: "Irán", dial: "+98" },
  { name: "Irlanda", dial: "+353" },
  { name: "Islandia", dial: "+354" },
  { name: "Islas Marshall", dial: "+692" },
  { name: "Islas Salomón", dial: "+677" },
  { name: "Israel", dial: "+972" },
  { name: "Italia", dial: "+39" },
  { name: "Jamaica", dial: "+1876" },
  { name: "Japón", dial: "+81" },
  { name: "Jordania", dial: "+962" },
  { name: "Kazajistán", dial: "+7" },
  { name: "Kenia", dial: "+254" },
  { name: "Kirguistán", dial: "+996" },
  { name: "Kiribati", dial: "+686" },
  { name: "Kuwait", dial: "+965" },
  { name: "Laos", dial: "+856" },
  { name: "Lesoto", dial: "+266" },
  { name: "Letonia", dial: "+371" },
  { name: "Líbano", dial: "+961" },
  { name: "Liberia", dial: "+231" },
  { name: "Libia", dial: "+218" },
  { name: "Liechtenstein", dial: "+423" },
  { name: "Lituania", dial: "+370" },
  { name: "Luxemburgo", dial: "+352" },
  { name: "Macedonia del Norte", dial: "+389" },
  { name: "Madagascar", dial: "+261" },
  { name: "Malasia", dial: "+60" },
  { name: "Malaui", dial: "+265" },
  { name: "Maldivas", dial: "+960" },
  { name: "Malí", dial: "+223" },
  { name: "Malta", dial: "+356" },
  { name: "Marruecos", dial: "+212" },
  { name: "Mauricio", dial: "+230" },
  { name: "Mauritania", dial: "+222" },
  { name: "México", dial: "+52" },
  { name: "Micronesia", dial: "+691" },
  { name: "Moldavia", dial: "+373" },
  { name: "Mónaco", dial: "+377" },
  { name: "Mongolia", dial: "+976" },
  { name: "Montenegro", dial: "+382" },
  { name: "Mozambique", dial: "+258" },
  { name: "Myanmar", dial: "+95" },
  { name: "Namibia", dial: "+264" },
  { name: "Nauru", dial: "+674" },
  { name: "Nepal", dial: "+977" },
  { name: "Nicaragua", dial: "+505" },
  { name: "Níger", dial: "+227" },
  { name: "Nigeria", dial: "+234" },
  { name: "Noruega", dial: "+47" },
  { name: "Nueva Zelanda", dial: "+64" },
  { name: "Omán", dial: "+968" },
  { name: "Países Bajos", dial: "+31" },
  { name: "Pakistán", dial: "+92" },
  { name: "Palaos", dial: "+680" },
  { name: "Panamá", dial: "+507" },
  { name: "Papúa Nueva Guinea", dial: "+675" },
  { name: "Paraguay", dial: "+595" },
  { name: "Perú", dial: "+51" },
  { name: "Polonia", dial: "+48" },
  { name: "Portugal", dial: "+351" },
  { name: "Reino Unido", dial: "+44" },
  { name: "República Centroafricana", dial: "+236" },
  { name: "República Checa", dial: "+420" },
  { name: "República del Congo", dial: "+242" },
  { name: "República Democrática del Congo", dial: "+243" },
  { name: "República Dominicana", dial: "+1809" },
  { name: "Ruanda", dial: "+250" },
  { name: "Rumania", dial: "+40" },
  { name: "Rusia", dial: "+7" },
  { name: "Samoa", dial: "+685" },
  { name: "San Cristóbal y Nieves", dial: "+1869" },
  { name: "San Marino", dial: "+378" },
  { name: "San Vicente y las Granadinas", dial: "+1784" },
  { name: "Santa Lucía", dial: "+1758" },
  { name: "Santo Tomé y Príncipe", dial: "+239" },
  { name: "Senegal", dial: "+221" },
  { name: "Serbia", dial: "+381" },
  { name: "Seychelles", dial: "+248" },
  { name: "Sierra Leona", dial: "+232" },
  { name: "Singapur", dial: "+65" },
  { name: "Siria", dial: "+963" },
  { name: "Somalia", dial: "+252" },
  { name: "Sri Lanka", dial: "+94" },
  { name: "Sudáfrica", dial: "+27" },
  { name: "Sudán", dial: "+249" },
  { name: "Sudán del Sur", dial: "+211" },
  { name: "Suecia", dial: "+46" },
  { name: "Suiza", dial: "+41" },
  { name: "Surinam", dial: "+597" },
  { name: "Tailandia", dial: "+66" },
  { name: "Tanzania", dial: "+255" },
  { name: "Tayikistán", dial: "+992" },
  { name: "Timor Oriental", dial: "+670" },
  { name: "Togo", dial: "+228" },
  { name: "Tonga", dial: "+676" },
  { name: "Trinidad y Tobago", dial: "+1868" },
  { name: "Túnez", dial: "+216" },
  { name: "Turkmenistán", dial: "+993" },
  { name: "Turquía", dial: "+90" },
  { name: "Tuvalu", dial: "+688" },
  { name: "Ucrania", dial: "+380" },
  { name: "Uganda", dial: "+256" },
  { name: "Uruguay", dial: "+598" },
  { name: "Uzbekistán", dial: "+998" },
  { name: "Vanuatu", dial: "+678" },
  { name: "Venezuela", dial: "+58" },
  { name: "Vietnam", dial: "+84" },
  { name: "Yemen", dial: "+967" },
  { name: "Yibuti", dial: "+253" },
  { name: "Zambia", dial: "+260" },
  { name: "Zimbabue", dial: "+263" },
];

/** Códigos telefónicos únicos, ordenados, para el select de prefijo. */
export const DIAL_CODES: string[] = Array.from(new Set(COUNTRIES.map((c) => c.dial))).sort(
  (a, b) => Number(a.replace("+", "")) - Number(b.replace("+", ""))
);
